{{- range .Values.deploymnet }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: '{{ .name }}'
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: '{{ .name }}'
  template:
    metadata:
      labels:
        app: '{{ .name }}'
    spec:
      containers:
        - resources: {}
          env:
          - name: COLOR
            value: '{{ .color }}'
          terminationMessagePath: /dev/termination-log
          name: '{{ .name }}'
          ports:
            - containerPort: {{ .containers.containerPort }}
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'quay.io/rhdevelopers/bgd:1.0.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
{{- end }}