apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: blue-green
  name: blue-green
spec:
  port:
    targetPort: 8080
  to:
  {{- with (index .Values.deploymnet 0) }}
    kind: Service
    name: {{ .name }}
    weight: 100
  {{- end }}