kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-1
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: {{ .Values.ReplicaNumber }}
  # selector:
  #   matchLabels:
  #     app: {{ .Release.Name }}-1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
#        rollme: {{ randAlphaNum 5 | quote }}  sulotion for l3 p1 t 2
      labels:
        app: {{ .Release.Name }}-1
    spec:
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
      containers:
        - resources: {}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containers.containerPort }} # In which port the Application is listening
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}      
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}-1
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: Always
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
          volumeMounts:
          - name: index-html
            mountPath: {{ .Values.volume.mount.path }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10