kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.containers.containerPort }}
  selector:
    app-1: {{ .Release.Name }}-1
    app-2: {{ .Release.Name }}-2