kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  alternateBackends:
  - kind: Service
    name: user1-hello-world
    weight: 50
  - kind: Service
    name: user1-hello-chart-service
    weight: 50