 deploy: 
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'quay.io/argo-helm-workshop/workshop-app'
    tag: 'chart_v2'

  service:
    servicePort: 8080

  argocd:
    syncwave:
      deployment: 5
      configmap: 1

deploy2: 
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'quay.io/argo-helm-workshop/workshop-app'
    tag: 'chart_v2'

  service:
    servicePort: 8080

  argocd:
    syncwave:
      deployment: 10
      configmap: 1
# argocd.syncwave.deployment
